### ISSUE TITLE
Provide functions to use `stringi` or `base` when there are features that RE2 is not supported.

### ISSUE THREAD

**Issue by qinwf** [qinwf/re2r#1]
`re2i` `re2i_extract` `re2i_replace` `re2i_match`: 

These functions will try to use RE2 first. If RE2 is not supported with the syntax, it will try to call stringi or stringr function.

**Comment by qinwf** [comment]
or base

**Comment by tdhock** [comment]
if you do that I would suggest a warning such as "using another regex engine, may have exponential time complexity"

but actually I think it would be better if you just stop with an error such as "re2r does not support regex with backreferences, try base::regexpr(perl=TRUE)"

that would make for easier maintenance, and guaranteed polynomial time complexity.

**Comment by qinwf** [comment]
I agree with you. It would be better to create a third party package to choose the regexp engine. 

Closed for now.
