### ISSUE TITLE
make: *** [dfa.o] Error 1

### ISSUE THREAD

**Issue by rexdouglass** [qinwf/re2r#12]
Hi all,

I'm having trouble installing re2r on Ubuntu 16.10 (Yakkety Yak). The error is below and appears to be related to a gcc problem (https://github.com/google/re2/issues/102)
I've been unable to resolve it by updating to the latest gcc (version 6.2.0 20161018 (Ubuntu 6.2.0-7ubuntu11) or including flags in the src/Makevars to try to force it to use clang instead (always defaults to g++)
"CC = clang
CXX = clang++"

Error below:

g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DNDEBUG  -I"/home/skynet2/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/skynet2/R/x86_64-pc-linux-gnu-library/3.3/RcppParallel/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-qk3a9o/r-base-3.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c dfa.cc -o dfa.o
dfa.cc: In constructor ‘re2::DFA::State::State()’:
dfa.cc:95:10: error: unknown array size in delete
   struct State {
          ^~~~~
dfa.cc: In member function ‘re2::DFA::State* re2::DFA::CachedState(int*, int, re2::uint)’:
dfa.cc:703:9: note: synthesized method ‘re2::DFA::State::State()’ first required here 
   State state;
         ^~~~~
/usr/lib/R/etc/Makeconf:139: recipe for target 'dfa.o' failed
make: *** [dfa.o] Error 1
ERROR: compilation failed for package ‘re2r’
* removing ‘/home/skynet2/R/x86_64-pc-linux-gnu-library/3.3/re2r’
Error: Command failed (1)

**Comment by qinwf** [comment]
Thanks for your report. Yes, this is a upstream related issue. I will push the workaround commit as in https://github.com/stefanv/re2/commit/86503cb89d82b723ae0bce35e1e09524910cd319

**Comment by rexdouglass** [comment]
Confirmed working, thanks for the quick help.
