### ISSUE TITLE
re2r doesn't work on colab

### ISSUE THREAD

**Issue by wangtz** [qinwf/re2r#25]
https://colab.sandbox.google.com/drive/1g9HP56CBmzBztlC5S7KdEq2yL4FYiHU4#scrollTo=XBCTEC_lwnhg

Error: Error in re2_detect(test_string, "(o.e)"): could not find function "re2_detect"

New to R, wondering if I need to do anything after installing the package?

Thanks,
Tiezhen

**Comment by kgjerde** [comment]
Be sure to load the package first:

`library(re2r)`

**Comment by wangtz** [comment]
Ah. I see. Thanks!
