### ISSUE TITLE
benchmark web page crashes my computer

### ISSUE THREAD

**Issue by tdhock** [qinwf/re2r#9]
@qinwf The docs you have written are really great, but I would recommend using PNG instead of plotly for the benchmark plots. On my computer with only 2GB of memory the system crashes. On another computer with 12GB it loads after a delay, and makes the memory usage of firefox increase by about 2GB. I think this can be fixed by rendering the plots as static PNG which are less memory intensive than plotly which uses javascript and SVG.

**Comment by qinwf** [comment]
Yes, I notice this too. Although the interactive plot is great, using ggplot2 with directlabels will get better page respond speed.
